-- ================================================================================
-- STUDY DESCRIPTION PRESETS (Multitenant - Postgres)
-- ================================================================================

CREATE TABLE IF NOT EXISTS study_description_presets (
    id SERIAL PRIMARY KEY,
    organization_id INTEGER NOT NULL,
    modality TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    created_by INTEGER NOT NULL,
    UNIQUE(organization_id, modality, description)
);

CREATE INDEX IF NOT EXISTS idx_presets_org_modality ON study_description_presets(organization_id, modality);

-- ================================================================================
-- YOUR STUDY DESCRIPTIONS (Insert for each organization)
-- ================================================================================
-- NOTE: Replace "1" with your actual organization_id
-- Users can also access /settings/study-descriptions to add more via the UI

-- CT Modality Presets
INSERT INTO study_description_presets (organization_id, modality, description, created_at, updated_at, created_by) VALUES
(1, 'CT', 'CT Abdo and pelvis with IV and oral Cont', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Abdomen', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Abdomen and pelvis', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Abdomen and pelvis oral contrast only', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Abdomen and pelvis with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Abdomen perfusion study', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Abdomen with & without contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Abdomen with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Acromioclavicular joint Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Acromioclavicular joint Lt', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Acromioclavicular joint Rt', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Adrenal Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Adrenal with contrast Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Adrenals with & without contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Adrenals With Contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Adrenals with contrast washout Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angio aorta coronary arteries', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angio aortic arch and carotid Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angio bicaval valve implantation Plan', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angio coronary artery graft', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angio triple phase for TAVI workup', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram abdomen', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram abdominal wall vessels', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram aorta', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram intracranial', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram lower limb Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram mesenteric artery', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram pulmonary', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram renal', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram spine', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiogram upper limb Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiography for TAVI workup', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Angiography thorax and abdomen', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Ankle Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Ankle Lt', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Ankle Rt', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Aorta abdominal', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Aorta abdominal with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Aorta thoracic', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Aorta thoracic with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Aorta whole', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Aorta whole with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Arthrogram ankle Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Arthrogram elbow Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Brain perfusion study', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Chest high resolution', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Chest with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Colon', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Face', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Head', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Head and neck', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Head and neck with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Head/Neck/Chest/Abd/Pelvis', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Head with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Hip Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Knee Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Liver', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Neck with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Pancreas', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Pelvis', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Shoulder Both', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Sinuses', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Spine cervical', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Spine lumbar', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Spine thoracic', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Thorax', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Thorax abdomen and pelvis', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Thorax and abdomen', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Thorax with contrast', datetime('now'), datetime('now'), 1),
(1, 'CT', 'CT Wrist Both', datetime('now'), datetime('now'), 1);

-- MRI Modality Presets
INSERT INTO study_description_presets (organization_id, modality, description, created_at, updated_at, created_by) VALUES
(1, 'MRI', 'Diffusion tensor MR brain', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MR Venography pulmonary', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Aorta abdominal', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Aorta thoracic', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Head', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Head and neck', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Lower limb Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Neck', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Renal Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRA Upper limb Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRCP', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Abdomen', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Abdomen and pelvis', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Ankle Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Ankle with contrast Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Aorta', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Arthrogram hip Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Arthrogram knee Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Axilla Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Brachial plexus', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Brain', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Brain with contrast', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Breast Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Breast with contrast Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Cardiac morphology function', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Cervix', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Colon', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Elbow Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Fetus', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Foot Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Hand Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Hip Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Hip with contrast Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI IAM', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Knee Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Knee with contrast Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Liver', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Liver with contrast', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Neck', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Orbit Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Pelvis', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Pelvis Gynae with contrast', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Pelvis with contrast', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Prostate', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Shoulder Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Shoulder with contrast Both', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Sinuses', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Spine cervical', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Spine lumbar', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Spine thoracic', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Thorax', datetime('now'), datetime('now'), 1),
(1, 'MRI', 'MRI Wrist Both', datetime('now'), datetime('now'), 1);

-- DEXA Modality Presets
INSERT INTO study_description_presets (organization_id, modality, description, created_at, updated_at, created_by) VALUES
(1, 'DEXA', 'DEXA Scan of femur Both', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DEXA Scan of femur Left', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DEXA Scan of femur Right', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DEXA Scan of forearm Both', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DEXA Scan of forearm Left', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DEXA Scan of forearm Right', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DXA Bone densitometry lateral spine', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DXA Vertebral morphometry', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'DXA Whole body', datetime('now'), datetime('now'), 1),
(1, 'DEXA', 'Bone densitometry DXA', datetime('now'), datetime('now'), 1);

-- PET Modality Presets
INSERT INTO study_description_presets (organization_id, modality, description, created_at, updated_at, created_by) VALUES
(1, 'PET', 'NM Brain PET FDG', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Cardiac rest PET FDG', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Cardiac stress PET FDG', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Cardiac viability scan FDG PET CT', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Choline whole body PET C11', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Choline whole body PET F18', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM F18 PSMA whole body PET CT', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Ga68 DOTATATE whole body PET CT', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Ga68 PSMA PET CT whole body', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Head and neck PET CT FDG', datetime('now'), datetime('now'), 1),
(1, 'PET', 'NM Whole body FDG PET CT', datetime('now'), datetime('now'), 1),
(1, 'PET', 'PET FDG Cardiac viability scan', datetime('now'), datetime('now'), 1),
(1, 'PET', 'PET FDG Whole body', datetime('now'), datetime('now'), 1),
(1, 'PET', 'Positron emission tomography with CT', datetime('now'), datetime('now'), 1);

-- XR Modality Presets
INSERT INTO study_description_presets (organization_id, modality, description, created_at, updated_at, created_by) VALUES
(1, 'XR', 'XR Abdomen', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Ankle Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR AP pelvis for hip surveillance', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Breast tomosynthesis Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Cervical spine', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Cervical spine flexion and extension', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Chest', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Chest and abdomen', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Chest PA view', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Clavicle Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Elbow Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Femur Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Fingers Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Foot Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Hand Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Hand and wrist Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Hip Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Humerus Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Intravenous urogram', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Knee Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Lumbar spine', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Lumbar spine and pelvis', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Mastoid Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Neck soft tissue', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Paranasal sinuses', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Pelvis', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Pelvis and hip Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Radius and ulna Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Sacroiliac joint Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Scapula Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Shoulder Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Skeletal survey', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Skull', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Spine cervical', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Spine lumbar', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Spine thoracic', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Thoracic spine', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Thorax', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Tibia and fibula Both', datetime('now'), datetime('now'), 1),
(1, 'XR', 'XR Wrist Both', datetime('now'), datetime('now'), 1);
